[package]
name = "sitegen"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.91"
handlebars = {version = "6.2.0", features=["dir_source"]}
serde = { version = "1.0", features = ["derive"] }
